baseURL = "https://louis-adriano.git.io"
languageCode = "en-us"
title = "Louis Adriano - Full Stack Developer"
theme = "papermod"

[params]
  defaultTheme = "auto"
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowShareButtons = true
  ShowReadingTime = true

[params.profileMode]
  enabled = true
  title = "Louis Adriano"
  subtitle = "Full Stack Developer | AI Enthusiast | Open Source Contributor"
  imageUrl = "/images/profile.jpg"
  imageWidth = 120
  imageHeight = 120

[[params.profileMode.buttons]]
  name = "Portfolio"
  url = "/portfolio"

[[params.profileMode.buttons]]
  name = "Blog"
  url = "/blog"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/louisadriano"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/louisadriano"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/louisadriano"

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 1

[[menu.main]]
  name = "Portfolio"
  url = "/portfolio"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/blog"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 4